/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include<stdint.h>


#define RCC_BASE_ADDR              0x40023800UL  // RCC Base Register Value

#define RCC_CFGR_REG_OFFSET        0x08UL        // RCC offset value for CFGR Register

#define RCC_CR_REG_OFFSET		   0x00UL        // RCC offset value for CR Register

#define RCC_CFGR_REG_ADDR          (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)

#define RCC_CR_REG_ADDR			   (RCC_BASE_ADDR + RCC_CR_REG_OFFSET)

#define GPIOA_BASE_ADDR            0x40020000UL

int main(void)
{
	// Enabling HSEON (RCC_CR Enable bit 16)

	uint32_t *ptrRCC_CR_REG = (uint32_t*) RCC_CR_REG_ADDR;
	*ptrRCC_CR_REG |= (1 << 16); // HSEON Enabled

	// Checking if the external clock is Stable (Checking HSERDY ie pin 17 on RCC_CR)

	while(! (*ptrRCC_CR_REG & (1 << 17)));


	// Switching the system clock to HSE

	uint32_t *ptrRCC_CFGR_REG = (uint32_t*) RCC_CFGR_REG_ADDR;
	*ptrRCC_CFGR_REG |= (1 << 0); // SW System clock switch to HSE Oscillator


	// Enabling HSE on MC01
	*ptrRCC_CFGR_REG &= ~(0x3 << 21); // Clear 21 and 22 Bit
	*ptrRCC_CFGR_REG |= (1 << 22);    // Set 22 bit


	//Configure MCO1 prescaler
	*ptrRCC_CFGR_REG |= ( 1 << 25); // Not required but only if prescalar is needed
	*ptrRCC_CFGR_REG |= ( 1 << 26); // Not required but only if prescalar is needed


/***********************************************************************************************/


	//2. Configure PA8 to AF0 mode to behave as MCO1 signal
/*
 * You are not expected to understand the below codes for the time being
 * because these codes are related to GPIO configurations,
 * which will be covered in later sections of this course.
 */

	//a ) Enable the peripheral clock for GPIOA peripheral

	 uint32_t *pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + 0x30);
	*pRCCAhb1Enr |= ( 1 << 0); //Enable GPIOA peripheral clock

	//b ) Configure the mode of GPIOA pin 8 as alternate function mode

	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	*pGPIOAModeReg &= ~( 0x3 << 16); //clear
	*pGPIOAModeReg |= ( 0x2 << 16);  //set

	//c ) Configure the alternation function register to set the mode 0 for PA8

	uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= ~( 0xf << 0);

/*****************************************************************************************************/
    /* Loop forever */
	for(;;);
}
